# Generated by Django 3.1.3 on 2020-12-26 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'db_table': 'categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'collection',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.TextField(blank=True, max_length=256, null=True)),
                ('created', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=250)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.TextField(blank=True, max_length=64, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('adress', models.TextField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=200)),
                ('size_xs', models.PositiveSmallIntegerField()),
                ('size_s', models.PositiveSmallIntegerField()),
                ('size_m', models.PositiveSmallIntegerField()),
                ('size_l', models.PositiveSmallIntegerField()),
                ('size_xl', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('number_of_sold', models.IntegerField()),
                ('image_1', models.ImageField(blank=True, upload_to=shop.models.image_folder1)),
                ('image_2', models.ImageField(blank=True, upload_to=shop.models.image_folder2)),
                ('image_3', models.ImageField(blank=True, upload_to=shop.models.image_folder3)),
                ('id_category', models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.CASCADE, to='shop.categories')),
                ('id_collection', models.ForeignKey(blank=True, db_column='id_collection', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.collection')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['number_of_sold'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('size', models.CharField(max_length=45)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.products')),
            ],
            options={
                'db_table': 'orderitem',
                'managed': True,
            },
        ),
    ]
