# Generated by Django 3.1.3 on 2020-11-29 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
