# Generated by Django 3.1.3 on 2020-12-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False, 'ordering': ['number_of_sold']},
        ),
    ]
