# Generated by Django 3.1.3 on 2020-12-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201201_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
