# Generated by Django 3.1.3 on 2020-12-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('adress', models.TextField(max_length=256)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
    ]
