# Generated by Django 3.1.3 on 2020-12-19 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
