# Generated by Django 3.1.3 on 2020-12-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
